# Using docker engine 20.10.13
version: "3.9"

services: 
  app:
    build: .
    image: cloud_app:latest
    container_name: cloud_app
    ports:
      - 3001:3000
    volumes:
      - ./:/usr/src
    depends_on:
      - db

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: