# Using docker engine 20.10.13
version: "3.9"

services: 
  app: &app
    image: cloud_app:prod
    container_name: cloud_app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    logging: &default_logging
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always

  replica:
    <<: *app
    ports:
      - 3001:3000

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      <<: *default_logging
    restart: always

  sidekiq:
    image: cloud_app:prod
    command: sidekiq
    environment:
      REDIS_URL: redis://redis:6379/0
    logging:
      <<: *default_logging
    restart: always

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq
    logging:
      <<: *default_logging
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    logging:
      <<: *default_logging
    restart: always

volumes:
  postgres:
  rabbit:
  redis: