# Using docker engine 20.10.13
version: "3.9"

services: 
  app:
    build: .
    image: cloud_app:latest
    container_name: cloud_app
    ports:
      - 3001:3000
    volumes:
      - ./:/usr/src
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0

  db:
    image: postgres:11.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres:/var/lib/postgresql/data

  sidekiq:
    build: .
    command: sidekiq
    volumes:
      - ./:/usr/src/
    environment:
      REDIS_URL: redis://redis:6379/0

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbit:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    volumes:
      - redis:/data

volumes:
  postgres:
  rabbit:
  redis: